export const ADD_USER_EXCHANGE = "ADD_USER_EXCHANGE"
export const LOAD_USER_EXCHANGE = "LOAD_USER_EXCHANGE"
export const LOAD_EXCHANGE_TRANSACTIONS = "LOAD_EXCHANGE_TRANSACTIONS"
export const ADD_CUSTOM_TRANSACTION = "ADD_CUSTOM_TRANSACTION"